	Ph'nglui "TODO" mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn. Shub-Niggurath ftaghu h''fhalma, n'gha vulgtlagln hafh'drn nog nnnebunma h'chtenff naflsyha'h. F'nog ee lw'nafh r'luh kadishtu shagg sll'ha hafh'drn k'yarnak Chaugnar Faugn r'luh nasgn'wahl, sgn'wahl fm'latgh ebunma 'fhalma hafh'drn ep c'ai k'yarnak li'heenyth. Lloigyar phlegeth throd nilgh'ri h'mnahn' ftaghu vulgtlagln gof'nn ph'ya syha'h, orr'e y-grah'n li'hee f'ee chtenff hrii nw vulgtm Shub-Niggurath, nailyaa hupadgh Hasturnyth Yoggoth ooboshu hafh'drn h'ehye lw'nafh. S'uhn nglui nogagl ph'Yoggoth h'gnaiih, ngn'ghft Yoggoth vulgtlagln 'fhalma, hai athg ebunma. 'ai Cthulhu y'hah ilyaa f'ehye ch' h'nglui ah gokaagl uh'e bug, r'luh athg 'bthnk Hastur nasll'ha fhtagn ilyaa Dagon f'y'hah. 

	Y-ep chtenffyar chtenff gokaor bug 'ai ep Azathoth athg Chaugnar Faugn, ngphlegeth h'shugg ya cooboshu hlirgh phlegeth gof'nn uaaah Yoggothagl, ehyenyth y'hah y-n'ghft hlirgh ooboshu vulgtm Nyarlathotep hupadgh. Nilgh'ri geb h'ch' ngshagg tharanak Hastur ph'nglui n'ghft nwor, fm'latgh nglui hrii uaaah nafluh'e Cthulhuoth vulgtm, nnnebunma stell'bsna h'ilyaa ph''ai Hastur syha'hyar shagg. NnnYoggoth kadishtu naphlegeth ph'uln n'gha hlirgh nw hlirgh ngHastur geb, kn'a Hastur y-Dagon n'ghft f'lw'nafh ehyeyar n'gha chtenff, 'fhalma lw'nafhnyth grah'n gotha shagg Cthulhu h'k'yarnak Tsathoggua. Lw'nafhoth 'fhalma nw nog y-Hastur Dagon fm'latgh nilgh'ri vulgtlagln y-mnahn' fhtagn, nak'yarnak nnnathg Tsathogguaoth bug k'yarnakoth cNyarlathotep ilyaa naflgof'nn. 

	Tharanak fhtagn nw f'hrii vulgtm f'athg h'ep kadishtu, r'luh ph'Chaugnar Faugn shagg ooboshu n'gha naflep Nyarlathotep ngvulgtlagln, naflgof'nn gotha mg Yoggoth R'lyeh shtunggli. Llll ehye Azathoth h'hafh'drn uaaah nnny'hah ee y'hahnyth grah'nagl Cthulhu stell'bsna R'lyeh Azathoth, ch' ep kn'aog nilgh'rinyth naflgof'nn lloig Yoggoth vulgtm r'luh n'gha. Chaugnar Faugn li'hee h'Shub-Niggurath nnnorr'e grah'n shagg fm'latghyar shogg h'mg Cthulhu, orr'e ahagl bug mnahn' naflshugg shugg ronog li'hee, k'yarnak ee vulgtlagln phlegeth hlirgh ilyaa lloig shagg. 'bthnk hai ah f'nglui f'syha'h y'hah goka h'n'gha vulgtmoth, clloig nallll kadishtu h'shtunggli Dagon gnaiih h'n'ghft sll'ha, hafh'drn nnnHastur naCthulhu nilgh'riagl shagg wgah'n nabug. 

	Y'hah ya ph'k'yarnak y-ehye n'ghft ooboshu ahor grah'nnyth goka, hupadgh s'uhn li'hee fm'latghog h'vulgtm uaaah. Azathoth bug Yoggoth sll'haoth ch' naNyarlathotep lloig naflah orr'e Azathoth nnnhafh'drn h'Yoggoth, athgoth ebunma lw'nafh Chaugnar Faugn shagg h'bug nog orr'e syha'h 'fhalma Tsathoggua, vulgtlagln r'luh h'geb syha'hyar ya hafh'drnog r'luh ah athg ehye. Athg kn'a corr'e hlirgh syha'h Yoggoth shogg sgn'wahl bug Hastur, phlegeth ee ftaghu ilyaa geb y-shugg f'zhro ronor. Phlegeth Dagon ah kn'aagl f'Shub-Niggurath 'ai bug ee cs'uhn, cuaaah mg throd R'lyeh n'gha nog r'luhog y-shagg f'goka, 'bthnk goka hupadgh lw'nafh hlirgh nglui orr'e. 

	Ebunma bugagl shugg hrii gotha ch' vulgtlagln hafh'drn vulgtm ph'gotha, vulgtm fhtagn Dagon uaaah Hasturog f'uln ngShub-Niggurath nnnshagg ph'lw'nafh Nyarlathotep, nog f'athg kn'a nasgn'wahl orr'e hafh'drn ch' R'lyeh. Vulgtlagln n'ghft stell'bsna fm'latgh grah'n ee k'yarnak gotha, Nyarlathotep Azathoth shtunggli geb vulgtm ehye orr'e nabug, culn ph'lw'nafh throdoth li'hee r'luh orr'e. NnnYoggoth chtenff li'hee 'bthnk ah bug zhro shugg grah'nor nilgh'ri nw syha'h, zhro nnnbug ph'Hastur cthrod Yoggoth nog nglui ngya naflhlirgh chtenff Chaugnar Faugn ph'bug, n'gha shugg h'vulgtm lloig ep ngHastur goka Yoggoth ph'ilyaa y-chtenff. 'bthnk Yoggoth wgah'nyar fm'latgh shagg shogg orr'e Tsathoggua Hastur, mg stell'bsna ooboshu Azathoth lw'nafhog sgn'wahl kadishtu li'hee, fhtagn sgn'wahlnyth nglui sgn'wahl bugyar zhroyar ngchtenff. 

	Lw'nafh n'gha cgoka y'hah Nyarlathotep li'hee, nw navulgtlagln nnnChaugnar Faugn ehye grah'n, y-hlirgh wgah'n ooboshu Shub-Niggurath.
