"B. dy'd not. Escap'd into walls and founde Place below.

"Sawe olde V. saye ye Sabaoth and learnt ye Way.

"Rais'd Yog-Sothoth thrice and was ye nexte Day deliver'd.

"F. soughte to wipe out all know'g howe to raise Those from Outside.

As the strong Argand blaze lit up the entire chamber the doctor saw that the wall opposite the door, between the two groups of torturing appliances in the corners, was covered with pegs from which hung a set of shapeless-looking robes of a rather dismal yellowish-white. But far more interesting were the two vacant walls, both of which were thickly covered with mystic symbols and formulae roughly chiselled in the smooth dressed stone. The damp floor also bore marks of carving; and with but little difficulty Willett deciphered a huge pentagram in the centre, with a plain circle about three feet wide half way between this and each corner. In one of these four circles, near where a yellowish robe had been flung carelessly down, there stood a shallow kylix of the sort found on the shelves above the whip-rack; and just outside the periphery was one of the Phaleron jugs from the shelves in the other room, its tag numbered 118. This was unstoppered, and proved upon inspection to be empty; but the explorer saw with a shiver that the kylix was not. Within its shallow area, and saved from scattering only by the absence of wind in this sequestered cavern, lay a small amount of a dry, dull-greenish efflorescent powder which must have belonged in the jug; and Willett almost reeled at the implications that came sweeping over him as he correlated little by little the several elements and antecedents of the scene. The whips and the instruments of torture, the dust or salts from the jug of "Materia", the two lekythoi from the "Custodes" shelf, the robes, the formulae on the walls, the notes on the pad, the hints from letters and legends, and the thousand glimpses, doubts, and suppositions which had come to torment the friends and parents of Charles Ward—all these engulfed the doctor in a tidal wave of horror as he looked at that dry greenish powder outspread in the pedestalled leaden kylix on the floor. 
