Excited beyond measure by his discovery, Ward shewed the book to the two curious workmen beside him. Their testimony is absolute as to the nature and genuineness of the finding, and Dr. Willett relies on them to help establish his theory that the youth was not mad when he began his major eccentricities. All the other papers were likewise in Curwen's handwriting, and one of them seemed especially portentous because of its inscription: "To Him Who Shal Come After, & How He May Gett Beyonde Time & ye Spheres." Another was in a cipher; the same, Ward hoped, as the Hutchinson cipher which had hitherto baffled him. A third, and here the searcher rejoiced, seemed to be a key to the cipher; whilst the fourth and fifth were addressed respectively to "Edw: Hutchinson, Armiger" and "Jedediah Orne, esq.", 'or Their Heir or Heirs, or Those Represent'g Them'. The sixth and last was inscribed: "Joseph Curwen his Life and Travells Bet'n ye yeares 1678 and 1687: Of Whither He Voyag'd, Where He Stay'd, Whom He Sawe, and What He Learnt."

3

We have now reached the point from which the more academic school of alienists date Charles Ward's madness. Upon his discovery the youth had looked immediately at a few of the inner pages of the book and manuscripts, and had evidently seen something which impressed him tremendously. Indeed, in shewing the titles to the workmen, he appeared to guard the text itself with peculiar care, and to labour under a perturbation for which even the antiquarian and genealogical significance of the find could hardly account. Upon returning home he broke the news with an almost embarrassed air, as if he wished to convey an idea of its supreme importance without having to exhibit the evidence itself. He did not even shew the titles to his parents, but simply told them that he had found some documents in Joseph Curwen's handwriting, "mostly in cipher", which would have to be studied very carefully before yielding up their true meaning. It is unlikely that he would have shewn what he did to the workmen, had it not been for their unconcealed curiosity. As it was he doubtless wished to avoid any display of peculiar reticence which would increase their discussion of the matter.

That night Charles Ward sat up in his room reading the new-found book and papers, and when day came he did not desist. His meals, on his urgent request when his mother called to see what was amiss, were sent up to him; and in the afternoon he appeared only briefly when the men came to install the Curwen picture and mantelpiece in his study. The next night he slept in snatches in his clothes, meanwhile wrestling feverishly with the unravelling of the cipher manuscript. In the morning his mother saw that he was at work on the photostatic copy of the Hutchinson cipher, which he had frequently shewn her before; but in response to her query he said that the Curwen key could not be applied to it. That afternoon he abandoned his work and watched the men fascinatedly as they finished their installation of the picture with its woodwork above a cleverly realistic electric log, setting the mock-fireplace and overmantel a little out from the north wall as if a chimney existed, and boxing in the sides with panelling to match the room's. The front panel holding the picture was sawn and hinged to allow cupboard space behind it. After the workmen went he moved his work into the study and sat down before it with his eyes half on the cipher and half on the portrait which stared back at him like a year-adding and century-recalling mirror.
// "TODO"
His parents, subsequently recalling his conduct at this period, give interesting details anent the policy of concealment which he practiced. Before servants he seldom hid any paper which he might be studying, since he rightly assumed that Curwen's intricate and archaic chirography would be too much for them. With his parents, however, he was more circumspect; and unless the manuscript in question were a cipher, or a mere mass of cryptic symbols and unknown ideographs (as that entitled "To Him Who Shal Come After, etc." seemed to be), he would cover it with some convenient paper until his caller had departed. At night he kept the papers under lock and key in an antique cabinet of his, where he also placed them whenever he left the room. He soon resumed fairly regular hours and habits, except that his long walks and other outside interests seemed to cease. The opening of school, where he now began his senior year, seemed a great bore to him; and he frequently asserted his determination never to bother with college. He had, he said, important special investigations to make, which would provide him with more avenues toward knowledge and the humanities than any university which the world could boast. 
